"""Import all ORM models so that SQLAlchemy metadata is fully populated."""

from app.models.user import SysUser, UserApiKey
from app.models.agent import (
    Agent,
    AgentBalance,
    AgentBalanceRecord,
    AgentImageBalance,
    AgentImageCreditRecord,
    AgentSubscriptionInventory,
    AgentSubscriptionInventoryRecord,
    AgentRedemptionAmountRule,
    AgentDailyLimit,
    AgentDailyLimitUsage,
    AgentSettlementRecord,
    AgentSettlementBatch,
    AgentSettlementBatchItem,
    AgentSubscriptionSaleRecord,
)
from app.models.channel import Channel
from app.models.model import (
    UnifiedModel,
    ModelChannelMapping,
    ModelImageResolutionRule,
    ModelPriceAdjustmentRule,
    ModelOverrideRule,
)
from app.models.log import (
    HealthCheckLog,
    RequestLog,
    RequestCacheSummary,
    SecurityRequestSnapshot,
    SecurityRiskEvent,
    SystemConfig,
    PlatformAnnouncement,
    OperationLog,
    UserBalance,
    ConsumptionRecord,
    UserImageBalance,
    ImageCreditRecord,
    ConversationSession,
    ConversationCheckpoint,
    UserSubscription,
    SubscriptionPlan,
    SubscriptionUsageCycle,
)
from app.models.redemption import RedemptionCode
from app.models.payment import (
    PaymentRechargeOrder,
    PaymentRechargeSettlement,
    AgentCashBalance,
    AgentCashLedger,
    AgentCashWithdrawal,
)
from app.models.promotion import (
    UserPromotionLink,
    UserPromotionRelation,
    UserPromotionReward,
)
from app.models.activity import DragonBoatLotteryEntry

__all__ = [
    "SysUser",
    "UserApiKey",
    "Agent",
    "AgentBalance",
    "AgentBalanceRecord",
    "AgentImageBalance",
    "AgentImageCreditRecord",
    "AgentSubscriptionInventory",
    "AgentSubscriptionInventoryRecord",
    "AgentRedemptionAmountRule",
    "AgentDailyLimit",
    "AgentDailyLimitUsage",
    "AgentSettlementRecord",
    "AgentSettlementBatch",
    "AgentSettlementBatchItem",
    "AgentSubscriptionSaleRecord",
    "Channel",
    "UnifiedModel",
    "ModelChannelMapping",
    "ModelImageResolutionRule",
    "ModelPriceAdjustmentRule",
    "ModelOverrideRule",
    "HealthCheckLog",
    "RequestLog",
    "RequestCacheSummary",
    "SecurityRequestSnapshot",
    "SecurityRiskEvent",
    "SystemConfig",
    "PlatformAnnouncement",
    "OperationLog",
    "UserBalance",
    "ConsumptionRecord",
    "UserImageBalance",
    "ImageCreditRecord",
    "ConversationSession",
    "ConversationCheckpoint",
    "UserSubscription",
    "SubscriptionPlan",
    "SubscriptionUsageCycle",
    "RedemptionCode",
    "PaymentRechargeOrder",
    "PaymentRechargeSettlement",
    "AgentCashBalance",
    "AgentCashLedger",
    "AgentCashWithdrawal",
    "UserPromotionLink",
    "UserPromotionRelation",
    "UserPromotionReward",
    "DragonBoatLotteryEntry",
]
